server:
  port: 8081
  servlet:
    context-path: /demo
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  expiration: 3600
  issuer: csmm



spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/csmm
    username: postgres
    password: 1122
  jpa:
    show-sql: true
  main:
    allow-circular-references: true
  mvc:
    problemdetails:
      enabled: true